# -*- coding: utf-8 -*-
"""TratamientoDatos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10gX1ENNjd6jDgy56LcnEdZ_ChCsvxtp_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

url = '/content/datos/datos_paises.csv'
df = pd.read_csv(url, sep=";")
print(df)

print('Filas y columnas:',df.shape)
print('Nombre columnas:',df.columns)

df.describe()

url = '/content/datos/paises.csv'
df_pop = pd.read_csv(url)
df_pop_ec = df_pop[df_pop["country"] == 'Ecuador' ]
print(df_pop_ec.head())
df_pop_ec.drop(['country'],axis=1)['population'].plot(kind='bar')

df_pop_col = df_pop[(df_pop["country"] == 'Colombia')]
anios = df_pop_ec['year'].unique()
pop_col = df_pop_col['population'].values
pop_ec = df_pop_ec['population'].values

df_plot = pd.DataFrame({'Colombia': pop_col,
                    'Ecuador': pop_ec}, 
                       index=anios)
df_plot.plot(kind='bar')

df_espanol = df.replace(np.nan, '', regex=True)
df_espanol = df_espanol[ df_espanol['languages'].str.contains('es') ]
df_espanol

df_espanol.set_index('alpha_3')[['population','area']].plot(kind='bar',rot=65,figsize=(20,10))

anomalies = []
def find_anomalies(data):
    data_std = data.std()
    data_mean = data.mean()
    anomaly_cut_off = data_std * 2
    lower_limit  = data_mean - anomaly_cut_off 
    upper_limit = data_mean + anomaly_cut_off
    print(lower_limit.iloc[0])
    print(upper_limit.iloc[0])

    # Generate outliers
    for index, row in data.iterrows():
        outlier = row # # obtener primer columna
        # print(outlier)
        if (outlier.iloc[0] > upper_limit.iloc[0]) or (outlier.iloc[0] < lower_limit.iloc[0]):
            anomalies.append(index)
    return anomalies

find_anomalies(df_espanol.set_index('alpha_3')[['population']])

df_espanol.drop([30,233], inplace=True)
df_espanol.set_index('alpha_3')[['population','area']].sort_values(["population"]).plot(kind='bar',rot=65,figsize=(20,10))